group:
  repos: |
    pulumi/pulumi
    pulumi/pulumi-java
  files:
    - source: pkg/tests/transpiled_examples
      dest: pkg/codegen/testing/test/testdata/transpiled_examples
      exclude: |
        .gitignore
        go.mod
      deleteOrphaned: true
