dist: goreleaser
project_name: pulumi-yaml
snapshot:
  name_template: "{{ .Version }}-SNAPSHOT"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
archives:
- id: language
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
  builds:
    - pulumi-language-yaml
- id: converter
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
  builds:
    - pulumi-converter-yaml
builds:
- id: pulumi-language-yaml
  binary: pulumi-language-yaml
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/pulumi/pulumi-yaml/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-language-yaml/
- id: pulumi-converter-yaml
  binary: pulumi-converter-yaml
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -s
  - -w
  - -X github.com/pulumi/pulumi-yaml/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-converter-yaml/