name: Periodically capture coverage
on:
  workflow_dispatch: {}
  schedule:
    # Run every 12 hours.
    - cron: '0 */12 * * *'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/stage-test.yml
    with:
      live-test: true
      coverage: true
    secrets:
      PULUMI_ACCESS_TOKEN:     ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID:       ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_CI_ROLE_ARN:         ${{ secrets.AWS_CI_ROLE_ARN }}
      ARM_CLIENT_ID:           ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:       ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID:           ${{ secrets.ARM_TENANT_ID }}
      CODECOV_TOKEN:           ${{ secrets.CODECOV_TOKEN }}
