name: dispatched-acceptance-test

on:
  repository_dispatch:
    types: [ run-acceptance-tests-command ]

jobs:
  comment-notification:
    # We only care about adding the result to the PR if it's a repository_dispatch event
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Create URL to the run output
        id: vars
        run: echo run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID >> "$GITHUB_OUTPUT"
      - name: Update with Result
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Please view the results of the PR Build + Acceptance Tests Run [Here][1]

            [1]: ${{ steps.vars.outputs.run-url }}
  test:
    uses: pulumi/pulumi-yaml/.github/workflows/stage-test.yml@main
    with:
      live-test: true
      commit-ref: refs/pull/${{ github.event.client_payload.pull_request.number }}/merge
      coverage: true
    secrets:
      PULUMI_ACCESS_TOKEN:     ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID:       ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_CI_ROLE_ARN:         ${{ secrets.AWS_CI_ROLE_ARN }}
      ARM_CLIENT_ID:           ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:       ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID:     ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID:           ${{ secrets.ARM_TENANT_ID }}
      CODECOV_TOKEN:           ${{ secrets.CODECOV_TOKEN }}
