on:
  push:
    branches: [ main ]
    paths: [ CHANGELOG.md ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release-pulumi-language-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Tags
        run: |
          git fetch --quiet --prune --tags
      - name: Set up Go 1.24.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Configure Go cache
        id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Set up Go cache
        uses: actions/cache@v4
        id: go-cache
        with:
          path: |
              ${{ steps.go-cache-paths.outputs.go-build }}
              ${{ steps.go-cache-paths.outputs.go-mod }}
          key: go-cache-${{ hashFiles('**/go.sum') }}
      - name: Get the latest version
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          args: latest
      - name: Add env vars
        run: |
          echo GORELEASER_CURRENT_TAG=${{ steps.latest.outputs.output }} >> $GITHUB_ENV
          echo RELEASE_NOTES_PATH=.changes/${{ steps.latest.outputs.output }}.md >> $GITHUB_ENV
      - name: Check if release exists
        # This lets us update CHANGELOG.md and with updated release notes without retriggering a release
        # that's already happened.
        id: check-release
        run: |
          if [ -z "$(git tag -l ${{ env.GORELEASER_CURRENT_TAG }})" ]; then
            echo "exists=false" >> "$GITHUB_OUTPUT"
          else
            echo "exists=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run GoReleaser
        if: steps.check-release.outputs.exists == 'false'
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -p 10 -f .goreleaser.yml --clean --skip=validate --timeout 60m0s --release-notes=${{ env.RELEASE_NOTES_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
